Added a PID controller class
UBCAgroBot/navigation-2019-2023 pull request #2
Opened 2022-09-30 21:42 UTC by CihanBosnali

2022-10-11 21:08 UTC, L0Lmaker requested changes

2022-10-11 21:08 UTC, L0Lmaker commented on controller.py
> +import time
Is there a better place to put this file? `helper_scripts` perhaps?

2022-10-11 21:34 UTC, L0Lmaker requested changes

2022-10-11 21:34 UTC, L0Lmaker commented on controller.py
> +    def __init__(self, Kp=0.1, Ki=0.0, Kd=0.0, useP=True, useI=True, useD=True):
convert to snake case

2022-10-11 21:34 UTC, L0Lmaker commented on controller.py
> +class PIDController:
convert to snake_case

2022-10-11 21:34 UTC, L0Lmaker commented on controller.py
> +
remove extra empty line here

2022-11-05 01:36 UTC, closed without merging

2022-11-05 01:36 UTC, CihanBosnali commented
After the requests are addressed, the controller is moved to the ROS workspace