Lymeng/performance test
UBCAgroBot/navigation-2019-2023 pull request #52
Opened 2023-01-08 20:19 UTC by NLmeng

2023-01-09 18:07 UTC, L0Lmaker requested changes

2023-01-09 18:07 UTC, L0Lmaker commented on test_pf.py
> +def run_algorithm(alg, vid_file):
If most of the function is the same, try to see if you can import and use the function

2023-01-09 18:07 UTC, L0Lmaker commented on test_pf.py
> +            processed_image, angle = alg.process_frame(frame, show=args.show)
Why is this handled differently?

2023-01-09 18:07 UTC, L0Lmaker commented on test_pf.py
> +import time
Add usage instructions in README.md file under the `Scripts` section.

2023-01-09 18:09 UTC, L0Lmaker requested changes

2023-01-09 18:09 UTC, L0Lmaker commented on test_pf.py
> +        "\naverage time to process a frame: %2.2f sec" % (1. * sum(all_time) / len(all_time)),
Can you convert this to average framerate

2023-01-10 23:04 UTC, NLmeng commented on test_pf.py
> +def run_algorithm(alg, vid_file):
Since run_algorithm(alg, vid_file) uses args, I don't think it is reusable in another function, unless I make changes to test_algorithms.py to where it takes in args. Also, I would need to make changes in the While loop to count the vanishing point uptime.

2023-01-10 23:05 UTC, NLmeng commented on test_pf.py
> +            processed_image, angle = alg.process_frame(frame, show=args.show)
It seems like that if-condition is not necessary. I copied that part from test_algorithms.py, but removing the extra if seems to work fine.

2023-01-10 23:09 UTC, NLmeng commented on test_pf.py
> +import time
added in a new commit

2023-01-10 23:09 UTC, NLmeng commented on test_pf.py
> +        "\naverage time to process a frame: %2.2f sec" % (1. * sum(all_time) / len(all_time)),
added in a new commit

2023-01-28 20:42 UTC, L0Lmaker commented on README.md
> +  - runs any of the algorithms against any video
```suggestion
  - runs performance tests on any of the algorithms against any video
  - reports `framerate`, `time-to-finish`, `vanishing point uptime`, `avg time to process frame`
```

2023-01-28 20:43 UTC, L0Lmaker approved these changes

2023-01-28 20:43 UTC, merged