Added filter to points in Lines, adapted algorithms according to changes, standardized outputs to return frame and angle
UBCAgroBot/navigation-2019-2023 pull request #6
Opened 2022-10-08 03:25 UTC by abhigyandabla

2022-10-08 03:56 UTC, L0Lmaker requested changes

2022-10-08 03:56 UTC, L0Lmaker commented on algorithms/utils/Lines.py
> +    # yPoints = []
Delete?

2022-10-08 03:56 UTC, L0Lmaker commented on algorithms/utils/Lines.py
> +                # yPoints.append(intersect[1])
same

2022-10-08 03:56 UTC, L0Lmaker commented on algorithms/utils/Lines.py
> +    return filtered
documentation

2022-10-08 03:56 UTC, L0Lmaker commented on algorithms/utils/Lines.py
> +        return (int(IntersectingX), int(IntersectingY))
update documentation for this change and any other methods that are changed

2022-10-08 03:56 UTC, L0Lmaker commented on algorithms/CenterRowAlgorithm.py
> +        vanishing_point = Lines.drawVanishingPoint(ellipse_frame, xPoints, yPoints)
python variable conventions, here and everywhere else.

2022-10-08 03:56 UTC, L0Lmaker commented on algorithms/MiniContoursAlgorithm.py
> +            cv2.waitKey(1)
See if we can remove unnecassary frame processes for algorithms

2022-10-11 18:02 UTC, AnimeAllstar commented
When will this be merged by? If this successfully standardizes the outputs, can we merge and move the other changes requested by @L0Lmaker to another PR?

2022-10-11 18:24 UTC, L0Lmaker commented
Yeah that should be doable @AnimeAllstar

I'll merge it in and ping you.

2022-10-11 21:22 UTC, L0Lmaker commented
> When will this be merged by? If this successfully standardizes the outputs, can we merge and move the other changes requested by @L0Lmaker to another PR?

So it looks like we can't merge this in yet. There are runtime errors when the code is run on videos.

2022-10-15 03:19 UTC, closed without merging